// pages/_app.tsx
import React from 'react';
import { AppProps } from 'next/app';
import RootLayout from '../components/layout';
import '../styles/global.css'; // Import your global styles here
import Head from 'next/head';
import Favicon from '../public/assets/images/logo-trans.png';

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <RootLayout>
      <Head>
        {/* Place your HTML and meta tags here */}
        <title>Game Town</title>
        <meta name="description" content="Generated by Next.js" />
        <link rel="icon" type="image/x-icon" href={Favicon.src}></link>
      </Head>
      <Component {...pageProps} />
    </RootLayout>
  );
};

export default MyApp;